version: '3'
services:
  mysql:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: study
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    hostname: mysqldocker
    volumes:
      - ./mysql/ddl:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
    tty: true
    stdin_open: true
